-- PostgreSQL 14+：连接到已创建的 seed 数据库后执行。
-- 订单业务示例的表结构和本地演示数据。
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(64) NOT NULL,
    user_id BIGINT NOT NULL,
    total_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_orders_order_no UNIQUE (order_no),
    CONSTRAINT ck_orders_user_id CHECK (user_id > 0),
    CONSTRAINT ck_orders_total_amount CHECK (total_amount > 0),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_orders_version CHECK (version >= 0)
);

-- 唯一约束已为 order_no 建索引；组合索引对应用户列表、超时扫描和默认分页。
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at, id);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders(created_at DESC, id DESC);

COMMENT ON TABLE orders IS '订单表';
COMMENT ON COLUMN orders.id IS '订单ID';
COMMENT ON COLUMN orders.order_no IS '订单号';
COMMENT ON COLUMN orders.user_id IS '用户上下文的ID，跨数据库不建外键';
COMMENT ON COLUMN orders.total_amount IS '订单总金额，正数且精度为分';
COMMENT ON COLUMN orders.status IS 'PENDING-待支付，PAID-已支付，CANCELLED-已取消，COMPLETED-已完成';
COMMENT ON COLUMN orders.version IS '乐观锁版本，防止并发支付和取消相互覆盖';
COMMENT ON COLUMN orders.created_at IS '创建时间';
COMMENT ON COLUMN orders.updated_at IS '更新时间，由聚合行为维护';

-- 新库中用户初始化脚本生成 user1/user2 的 ID 为 1/2。
INSERT INTO orders (order_no, user_id, total_amount, status) VALUES
('ORD1000000001', 1, 99.99, 'PENDING'),
('ORD1000000002', 1, 199.99, 'PAID'),
('ORD1000000003', 2, 299.99, 'COMPLETED')
ON CONFLICT (order_no) DO NOTHING;
